export const styles = {
  overlay: {
    position: 'fixed' as const,
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex' as const,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    zIndex: 1000,
  },
  modal: {
    background: 'white',
    borderRadius: 18,
    padding: 30,
    width: '90%',
    maxWidth: 400,
    maxHeight: '90vh',
    overflowY: 'auto' as const,
    boxShadow: '0 8px 32px rgba(0,0,0,0.2)',
  },
  title: {
    fontSize: 20,
    fontWeight: 600,
    marginBottom: 20,
    color: '#1d1d1f',
  },
  form: {
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: 16,
  },
  inputGroup: {
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: 8,
  },
  label: {
    fontSize: 14,
    color: '#3a3a3c',
    fontWeight: 500,
  },
  input: {
    padding: '12px 16px',
    borderRadius: 12,
    border: '1px solid #c7c7cc',
    backgroundColor: '#f5f5f7',
    fontSize: 16,
    color: '#1d1d1f',
    outline: 'none',
  },
  buttonGroup: {
    display: 'flex' as const,
    gap: 12,
    marginTop: 16,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: '#e5e5ea',
    color: '#1d1d1f',
    border: 'none',
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    fontWeight: 600,
    cursor: 'pointer',
  },
  saveButton: {
    flex: 1,
    backgroundColor: '#007aff',
    color: 'white',
    border: 'none',
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    fontWeight: 600,
    cursor: 'pointer',
    opacity: 1,
  },
  success: {
    color: '#34c759',
    fontSize: 14,
    margin: 0,
    textAlign: 'center' as const,
  },
  error: {
    color: '#ff3b30',
    fontSize: 14,
    margin: 0,
    textAlign: 'center' as const,
  },
};
