export const styles = {
  empty: {
    textAlign: 'center' as const,
    padding: 40,
    color: '#86868b',
    backgroundColor: '#fafafa',
    borderRadius: 12,
    fontSize: 16,
  },
  tableContainer: {
    overflowX: 'auto' as const,
    borderRadius: 12,
    border: '1px solid #e5e5ea',
    backgroundColor: 'white',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: 14,
  },
  th: {
    backgroundColor: '#fafafa',
    padding: '8px 12px',
    textAlign: 'left' as const,
    fontWeight: 600,
    color: '#1d1d1f',
    borderBottom: '1px solid #e5e5ea',
    fontSize: 12,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
  },
  tr: {
    borderBottom: '1px solid #f5f5f7',
  },
  td: {
    padding: '8px 12px',
    color: '#1d1d1f',
    fontSize: 13,
  },
  badgeAdmin: {
    backgroundColor: '#5856d6',
    color: 'white',
    padding: '2px 8px',
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
  },
  badgeMember: {
    backgroundColor: '#e5e5ea',
    color: '#1d1d1f',
    padding: '2px 8px',
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
  },
  badgeActive: {
    backgroundColor: '#e8f5e9',
    color: '#34c759',
    padding: '2px 8px',
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 600,
  },
  badgeInactive: {
    backgroundColor: '#fff2f2',
    color: '#ff3b30',
    padding: '2px 8px',
    borderRadius: 6,
    fontSize: 11,
    fontWeight: 600,
  },
  deleteBtn: {
    backgroundColor: '#fff2f2',
    color: '#ff3b30',
    border: '1px solid #ffd4d4',
    borderRadius: 8,
    padding: '4px 8px',
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
  },
  editBtn: {
    backgroundColor: '#f5f5f7',
    color: '#007aff',
    border: '1px solid #d4e6ff',
    borderRadius: 8,
    padding: '4px 8px',
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    marginRight: 6,
  },
} as const;
