"""Initial migration

Revision ID: 3a22d42acfa1
Revises: 
Create Date: 2026-04-30 17:26:28.506719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a22d42acfa1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anggota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('no_wa', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anggota_email'), 'anggota', ['email'], unique=True)
    op.create_index(op.f('ix_anggota_id'), 'anggota', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_name', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('footer_text', sa.String(length=255), nullable=True),
    sa.Column('landing_headline', sa.String(length=255), nullable=True),
    sa.Column('landing_description', sa.Text(), nullable=True),
    sa.Column('landing_features', sa.Text(), nullable=True),
    sa.Column('social_instagram', sa.String(length=100), nullable=True),
    sa.Column('social_linkedin', sa.String(length=100), nullable=True),
    sa.Column('social_website', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('funding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anggota_id', sa.Integer(), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=False),
    sa.Column('tujuan_usaha', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DIAJUKAN', 'DISETUJUI', 'DICAIRKAN', name='statusfunding'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anggota_id'], ['anggota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_id'), 'funding', ['id'], unique=False)
    op.create_table('pinjaman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anggota_id', sa.Integer(), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=False),
    sa.Column('margin_persen', sa.Float(), nullable=False),
    sa.Column('tenor_bulan', sa.Integer(), nullable=False),
    sa.Column('angsuran_per_bulan', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DIAJUKAN', 'DITERIMA', 'AKTIF', 'LUNAS', name='statuspinjaman'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anggota_id'], ['anggota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pinjaman_id'), 'pinjaman', ['id'], unique=False)
    op.create_table('simpanan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anggota_id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.String(length=20), nullable=False),
    sa.Column('nominal', sa.Float(), nullable=False),
    sa.Column('saldo_setelah', sa.Float(), nullable=False),
    sa.Column('keterangan', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anggota_id'], ['anggota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simpanan_id'), 'simpanan', ['id'], unique=False)
    op.create_table('angsuran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pinjaman_id', sa.Integer(), nullable=False),
    sa.Column('anggota_id', sa.Integer(), nullable=False),
    sa.Column('bulan_ke', sa.Integer(), nullable=False),
    sa.Column('nominal_angsuran', sa.Float(), nullable=False),
    sa.Column('tanggal_jatuh_tempo', sa.DateTime(), nullable=True),
    sa.Column('tanggal_bayar', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('BELUM_BAYAR', 'SUDAH_BAYAR', name='statusangsuran'), nullable=True),
    sa.Column('denda', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['anggota_id'], ['anggota.id'], ),
    sa.ForeignKeyConstraint(['pinjaman_id'], ['pinjaman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_angsuran_id'), 'angsuran', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_angsuran_id'), table_name='angsuran')
    op.drop_table('angsuran')
    op.drop_index(op.f('ix_simpanan_id'), table_name='simpanan')
    op.drop_table('simpanan')
    op.drop_index(op.f('ix_pinjaman_id'), table_name='pinjaman')
    op.drop_table('pinjaman')
    op.drop_index(op.f('ix_funding_id'), table_name='funding')
    op.drop_table('funding')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_anggota_id'), table_name='anggota')
    op.drop_index(op.f('ix_anggota_email'), table_name='anggota')
    op.drop_table('anggota')
    # ### end Alembic commands ###
