export const styles = {
  container: {
    minHeight: '100vh',
    display: 'flex' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#f5f5f7',
    backgroundImage: 'radial-gradient(circle at 20% 50%, rgba(0, 122, 255, 0.05) 0%, transparent 50%), radial-gradient(circle at 80% 50%, rgba(175, 82, 222, 0.05) 0%, transparent 50%)',
    padding: 20,
    fontFamily: 'inherit',
  },
  card: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 24,
    padding: '48px 40px',
    maxWidth: 420,
    width: '100%',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.08), 0 1px 3px rgba(0, 0, 0, 0.04), inset 0 1px 0 rgba(255, 255, 255, 0.7)',
    backdropFilter: 'blur(20px)',
    border: '1px solid rgba(255, 255, 255, 0.18)',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
  },
  headerIcon: {
    fontSize: 48,
    textAlign: 'center' as const,
    marginBottom: 16,
  },
  title: {
    fontSize: 32,
    fontWeight: 700,
    color: '#1d1d1f',
    marginBottom: 8,
    textAlign: 'center' as const,
    letterSpacing: '-0.5px',
  },
  subtitle: {
    fontSize: 15,
    color: '#86868b',
    textAlign: 'center' as const,
    marginBottom: 32,
    lineHeight: 1.5,
  },
  guideNote: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
    textAlign: 'center' as const,
    marginBottom: 16,
    padding: '8px 12px',
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
    borderLeft: '3px solid #007aff',
  },
  error: {
    backgroundColor: '#fff2f2',
    color: '#ff3b30',
    padding: '14px 18px',
    borderRadius: 12,
    fontSize: 14,
    border: '1.5px solid #ffd4d4',
    display: 'flex' as const,
    alignItems: 'center' as const,
    gap: 10,
    marginBottom: 8,
  },
  errorIcon: {
    fontSize: 18,
  },
  success: {
    backgroundColor: '#f2fff2',
    color: '#34c759',
    padding: '14px 18px',
    borderRadius: 12,
    fontSize: 14,
    border: '1.5px solid #d4ffd4',
    display: 'flex' as const,
    alignItems: 'center' as const,
    gap: 10,
    marginBottom: 8,
  },
  successIcon: {
    fontSize: 18,
  },
  divider: {
    display: 'flex' as const,
    alignItems: 'center' as const,
    margin: '28px 0',
    gap: 16,
  },
  dividerText: {
    color: '#86868b',
    fontSize: 13,
    fontWeight: 500,
  },
  switchText: {
    textAlign: 'center' as const,
    fontSize: 15,
    color: '#86868b',
    margin: 0,
  },
  link: {
    color: '#007aff',
    textDecoration: 'none' as const,
    fontWeight: 600,
    transition: 'color 0.2s ease',
  },
} as const;
