export const styles = {
  form: {
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: 16,
  },
  inputGroup: {
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: 8,
  },
  label: {
    fontSize: 14,
    fontWeight: 600,
    color: '#1d1d1f',
  },
  input: {
    padding: '14px 16px',
    borderRadius: 12,
    border: '2px solid #e5e5ea',
    fontSize: 16,
    backgroundColor: 'white',
    color: '#1d1d1f',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  select: {
    padding: '14px 16px',
    borderRadius: 12,
    border: '2px solid #e5e5ea',
    fontSize: 16,
    backgroundColor: 'white',
    color: '#1d1d1f',
    outline: 'none',
    cursor: 'pointer' as const,
  },
  button: {
    background: 'linear-gradient(135deg, #007aff 0%, #5856d6 100%)',
    color: 'white',
    border: 'none',
    borderRadius: 24,
    padding: '14px 24px',
    fontSize: 16,
    fontWeight: 600,
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(0,122,255,0.3)',
    marginTop: 8,
  },
  success: {
    background: 'rgba(52,199,89,0.1)',
    color: '#34c759',
    padding: '12px 16px',
    borderRadius: 12,
    fontSize: 14,
  },
  error: {
    background: 'rgba(255,59,48,0.1)',
    color: '#ff3b30',
    padding: '12px 16px',
    borderRadius: 12,
    fontSize: 14,
  },
};
