export const styles = {
  container: {
    backgroundColor: '#f5f5f7',
    fontFamily: 'inherit',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  title: {
    fontSize: 24,
    fontWeight: 600,
    marginBottom: 8,
    color: '#1d1d1f',
  },
  guideNote: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic' as const,
    padding: '8px 12px',
    backgroundColor: '#f9f9f9',
    borderRadius: 8,
    borderLeft: '3px solid #007aff',
  },
  card: {
    marginBottom: 20,
  },
  select: {
    width: '100%',
    padding: '14px 16px',
    fontSize: 15,
    fontFamily: 'inherit',
    color: '#1D1D1F',
    backgroundColor: '#FFFFFF',
    border: '1.5px solid rgba(0, 0, 0, 0.1)',
    borderRadius: 16,
    outline: 'none',
    boxSizing: 'border-box' as const,
    appearance: 'none' as const,
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%2386868B' d='M2 4l4 4 4-4'/%3E%3C/svg%3E")`,
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 16px center',
  },
  textarea: {
    width: '100%',
    padding: '14px 16px',
    fontSize: 15,
    fontFamily: 'inherit',
    color: '#1D1D1F',
    backgroundColor: '#FFFFFF',
    border: '1.5px solid rgba(0, 0, 0, 0.1)',
    borderRadius: 16,
    outline: 'none',
    boxSizing: 'border-box' as const,
    resize: 'vertical' as const,
  },
  successMsg: {
    padding: 12,
    backgroundColor: 'rgba(52, 199, 89, 0.1)',
    color: '#34C759',
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 500,
    marginBottom: 16,
  },
  errorMsg: {
    padding: 12,
    backgroundColor: 'rgba(255, 59, 48, 0.1)',
    color: '#FF3B30',
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 500,
    marginBottom: 16,
  },
};
